version: "3.9"
services:
  traffic-watch-backend:
    container_name: traffic-watch-backend
    build:
      context: ./traffic-watch-backend
      dockerfile: ./Dockerfile
    image: server
    ports:
      - "3000:3000"
    volumes:
      - ./traffic-watch-backend:/traffic-watch-backend
    command: npm run start:dev
  traffic-watch-frontend:
    container_name: traffic-watch-frontend
    build:
      context: ./traffic-watch-frontend
      dockerfile: ./Dockerfile
    image: traffic-watch-frontend
    cpus: "2"
    mem_reservation: "2G"
    mem_limit: "4G"
    ports:
      - "4000:4000"
    volumes:
      - ./traffic-watch-frontend:/traffic-watch-frontend
    command: npm run start